In [1]:
#importing libraries
import pandas as pd
import numpy as np

In [3]:
# reading the dataset into a dataframe
df= pd.read_csv('spam.csv')
df

In [4]:
#checking the number of rows and columns
df.shape

(5572, 2)

In [7]:
#droping possible duplicates
df.drop_duplicates(inplace = True)

In [9]:
#checking the number of rows and columns
df.shape

(5157, 2)

In [10]:
#checking for nulls
df.isnull().sum()

Category    0
Message     0
dtype: int64

In [12]:
#checking for the unique values in the category columns
df['Category'].unique()

array(['ham', 'spam'], dtype=object)

In [15]:
#converting the numeric- spam = 1 and ham = 0
df['Category'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)

In [16]:
df['Category'].unique()

array([0, 1])

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5157 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Category  5157 non-null   int64 
 1   Message   5157 non-null   object
dtypes: int64(1), object(1)
memory usage: 120.9+ KB


In [19]:
# defining x and y
x = df['Message']
y= df['Category']

In [27]:
#importing machine learning packages
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

In [28]:
#spliting our data into train and test data
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [31]:
#converting the x_train into numeric using count vectorizer
cv= CountVectorizer(stop_words = 'english')
x_train_count = cv.fit_transform(x_train)

In [32]:
#creating and training the model
model = MultinomialNB()
model.fit(x_train_count, y_train)

MultinomialNB()

In [36]:
#pretesting the model
spam = ['Congratulations!, winner of the cash']
spam_count = cv.transform(spam)
model.predict(spam_count)

array([1])

In [37]:
# pretesing
ham = ['I love you']
ham_count = cv.transform(ham)
model.predict(ham_count)

array([0])

In [39]:
#Testing the model

#transform x_test
x_test_count = cv.transform(x_test)

#testing the model proper
model.score(x_test_count, y_test) #returns the mean accuracy on the given test data and labels

0.9854651162790697

In [44]:
# predicting message
def predict(message):
    input_message = cv.transform([message]).toarray()
    result = model.predict(input_message)
    print(result)
predict('Congratulations!, winner of the cash') 

[1]


In [45]:
# Building web applicatio
import streamlit as st

In [48]:
!jupyter nbconvert --to script Spam_filter.ipynb


[NbConvertApp] Converting notebook Spam_filter.ipynb to script
[NbConvertApp] Writing 2235 bytes to Spam_filter.py


^C
